# build environment
FROM node:current-alpine3.15 as build

WORKDIR /app

COPY package.json /app/package.json

RUN npm install

COPY . /app/

# give permission to read and write
RUN chown -R node /app/node_modules 

RUN npm run build

# production environment
FROM nginx
COPY --from=build /app/build /usr/share/nginx/html
# copy config file
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]